/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_cine.Formularios;

/**
 *
 * @author Emely
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        botonPrincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonFuncion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botonAdministracion = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonVentas = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonReportes = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonPeliculas = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        app_name = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        app_name1 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        fecha1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(17, 9, 22));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPrincipal.setBackground(new java.awt.Color(255, 0, 76));
        botonPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPrincipal.setPreferredSize(new java.awt.Dimension(270, 70));
        botonPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonPrincipalMousePressed(evt);
            }
        });
        botonPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Principal");
        botonPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home32.png"))); // NOI18N
        botonPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        Menu.add(botonPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        BotonFuncion.setBackground(new java.awt.Color(255, 0, 76));
        BotonFuncion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonFuncion.setPreferredSize(new java.awt.Dimension(270, 70));
        BotonFuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonFuncionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonFuncionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonFuncionMousePressed(evt);
            }
        });
        BotonFuncion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Funcion");
        BotonFuncion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 70, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magazine 32.png"))); // NOI18N
        BotonFuncion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Menu.add(BotonFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        botonAdministracion.setBackground(new java.awt.Color(255, 0, 76));
        botonAdministracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAdministracion.setPreferredSize(new java.awt.Dimension(270, 70));
        botonAdministracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAdministracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAdministracionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAdministracionMousePressed(evt);
            }
        });
        botonAdministracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Administracion");
        botonAdministracion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/config 32.png"))); // NOI18N
        botonAdministracion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        Menu.add(botonAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, 70));

        botonVentas.setBackground(new java.awt.Color(255, 0, 76));
        botonVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonVentas.setPreferredSize(new java.awt.Dimension(270, 70));
        botonVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVentasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVentasMousePressed(evt);
            }
        });
        botonVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ventas");
        botonVentas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shop 32.png"))); // NOI18N
        botonVentas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        Menu.add(botonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        botonReportes.setBackground(new java.awt.Color(255, 0, 76));
        botonReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonReportes.setPreferredSize(new java.awt.Dimension(270, 70));
        botonReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReportesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonReportesMousePressed(evt);
            }
        });
        botonReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Reportes");
        botonReportes.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        botonReportes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Menu.add(botonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));

        botonPeliculas.setBackground(new java.awt.Color(255, 0, 76));
        botonPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPeliculas.setPreferredSize(new java.awt.Dimension(270, 70));
        botonPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPeliculasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPeliculasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonPeliculasMousePressed(evt);
            }
        });
        botonPeliculas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Peliculas");
        botonPeliculas.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movie 32.png"))); // NOI18N
        botonPeliculas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Menu.add(botonPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        app_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cinema_Showtime_100x100.png"))); // NOI18N
        Menu.add(app_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, 100));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, 10));

        app_name1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name1.setForeground(new java.awt.Color(255, 255, 255));
        app_name1.setText("CINEMA SHOWTIME");
        Menu.add(app_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        Header.setBackground(new java.awt.Color(17, 9, 22));

        fecha.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("HORA");

        fecha1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        fecha1.setForeground(new java.awt.Color(255, 255, 255));
        fecha1.setText("USUARIO: ");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(621, Short.MAX_VALUE)
                .addComponent(fecha)
                .addGap(58, 58, 58))
            .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeaderLayout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(fecha1)
                    .addContainerGap(541, Short.MAX_VALUE)))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeaderLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(139, Short.MAX_VALUE)))
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 750, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPrincipalMouseEntered
       
    }//GEN-LAST:event_botonPrincipalMouseEntered

    private void botonPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPrincipalMouseExited
        
    }//GEN-LAST:event_botonPrincipalMouseExited

    private void botonPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPrincipalMousePressed
      
    }//GEN-LAST:event_botonPrincipalMousePressed

    private void BotonFuncionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonFuncionMouseEntered
       
    }//GEN-LAST:event_BotonFuncionMouseEntered

    private void BotonFuncionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonFuncionMouseExited
      
    }//GEN-LAST:event_BotonFuncionMouseExited

    private void BotonFuncionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonFuncionMousePressed
       
    }//GEN-LAST:event_BotonFuncionMousePressed

    private void botonAdministracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAdministracionMouseEntered
      
    }//GEN-LAST:event_botonAdministracionMouseEntered

    private void botonAdministracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAdministracionMouseExited
      
    }//GEN-LAST:event_botonAdministracionMouseExited

    private void botonAdministracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAdministracionMousePressed
       
    }//GEN-LAST:event_botonAdministracionMousePressed

    private void botonVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseEntered
       
    }//GEN-LAST:event_botonVentasMouseEntered

    private void botonVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseExited
        
    }//GEN-LAST:event_botonVentasMouseExited

    private void botonVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMousePressed
        
    }//GEN-LAST:event_botonVentasMousePressed

    private void botonReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportesMouseEntered
       
    }//GEN-LAST:event_botonReportesMouseEntered

    private void botonReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportesMouseExited
       
    }//GEN-LAST:event_botonReportesMouseExited

    private void botonReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportesMousePressed
        
    }//GEN-LAST:event_botonReportesMousePressed

    private void botonPeliculasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPeliculasMouseEntered
        
    }//GEN-LAST:event_botonPeliculasMouseEntered

    private void botonPeliculasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPeliculasMouseExited
       
    }//GEN-LAST:event_botonPeliculasMouseExited

    private void botonPeliculasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPeliculasMousePressed
        
    }//GEN-LAST:event_botonPeliculasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonFuncion;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel app_name;
    private javax.swing.JLabel app_name1;
    private javax.swing.JPanel botonAdministracion;
    private javax.swing.JPanel botonPeliculas;
    private javax.swing.JPanel botonPrincipal;
    private javax.swing.JPanel botonReportes;
    private javax.swing.JPanel botonVentas;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fecha1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
